#!/bin/bash
VAR_INTEGER=1
VAR_FLOAT=0.2
VAR_STRING_SINGLE_QUOTE='VAR_INTEGER=${VAR_INTEGER}'
VAR_STRING_DOUBLE_QUOTE="VAR_INTEGER=${VAR_INTEGER}"
VAR_TEXT=some_text
VAR_FILECONTENT=$(head -n 5 /etc/passwd)

echo ${VAR_INTEGER}
echo ${VAR_FLOAT}
echo ${VAR_STRING_SINGLE_QUOTE}
echo ${VAR_STRING_DOUBLE_QUOTE}
echo ${VAR_TEXT}
echo ${VAR_FILECONTENT}